language: android
jdk:
  - oraclejdk8
branches:
  only:
  - test/travis
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - build-tools-25.0.0
    - android-25
    - android-19
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
before_install:
  - echo no | android create avd -f -n emulator -t android-19 --abi armeabi-v7a
  - emulator -avd emulator -no-audio -no-window -wipe-data -no-skin &
  - android-wait-for-emulator
before_script:
  - cd todoapp/
  - ./gradlew clean
script:
  - ./gradlew cAT --stacktrace
  - cat /home/travis/build/senseobservationsystems/android-architecture/todoapp/app/build/reports/androidTests/connected/flavors/MOCK/index.html